# Generated by Django 5.2.4 on 2025-08-24 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostEstimation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("kitchen", "Modular Kitchen"),
                            ("wall-paneling", "Wall Paneling"),
                            ("false-ceiling", "False Ceiling"),
                            ("interior-decoration", "Interior Decoration"),
                            ("wardrobe", "Wardrobe"),
                            ("complete-home", "Complete Home"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "kitchen_package",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "wall_paneling_package",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "false_ceiling_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "interior_package",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "wardrobe_package",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField(blank=True, null=True)),
                ("area", models.FloatField()),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "features_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("gst", models.DecimalField(decimal_places=2, max_digits=12)),
                ("final_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("include_gst", models.BooleanField(default=True)),
                ("additional_features", models.JSONField(default=list)),
                ("package_description", models.TextField(blank=True, null=True)),
                ("package_features", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
