# Generated by Django 5.2.4 on 2025-08-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("KIT", "Kitchen"),
                            ("LIV", "Living Room"),
                            ("BED", "Bedroom"),
                            ("BATH", "Bathroom"),
                            ("WARD", "Wardrobe"),
                            ("OFF", "Office"),
                            ("COM", "Complete Home"),
                        ],
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("main_image", models.ImageField(upload_to="portfolio/main_images/")),
                ("description", models.TextField()),
                ("detailed_description", models.TextField()),
                ("completion_time", models.CharField(max_length=100)),
                ("budget", models.CharField(max_length=100)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Portfolio Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/images/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "portfolio_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.portfolioitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=255)),
                (
                    "portfolio_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="portfolio.portfolioitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "before_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/case_studies/before/",
                    ),
                ),
                (
                    "after_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio/case_studies/after/"
                    ),
                ),
                ("challenges", models.TextField(blank=True)),
                ("solutions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_studies",
                        to="portfolio.portfolioitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", models.CharField(max_length=255)),
                (
                    "portfolio_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="portfolio.portfolioitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.URLField()),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "portfolio_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="portfolio.portfolioitem",
                    ),
                ),
            ],
        ),
    ]
