# Generated by Django 5.2.4 on 2025-08-13 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("repair", "Repair Request"),
                            ("video", "Video Consultancy"),
                            ("onsite", "On-site Free Consultancy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 10-15 digits and may include country code",
                                regex="^\\+?[0-9]{10,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "service_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("issue_description", models.TextField(blank=True, null=True)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not specified"),
                            ("10:00", "10:00 AM"),
                            ("11:00", "11:00 AM"),
                            ("12:00", "12:00 PM"),
                            ("14:00", "2:00 PM"),
                            ("15:00", "3:00 PM"),
                            ("16:00", "4:00 PM"),
                            ("morning", "Morning (9 AM - 12 PM)"),
                            ("afternoon", "Afternoon (12 PM - 4 PM)"),
                            ("evening", "Evening (4 PM - 7 PM)"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("complete_address", models.TextField(blank=True, null=True)),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not specified"),
                            ("kitchen", "Modular Kitchen"),
                            ("wardrobe", "Wardrobe"),
                            ("living-room", "Living Room"),
                            ("bedroom", "Bedroom"),
                            ("complete-home", "Complete Home"),
                            ("office", "Office Interior"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("project_details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("status_changed", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["service_number"], name="services_se_service_8de4a8_idx"
                    ),
                    models.Index(
                        fields=["service_type"], name="services_se_service_ec2737_idx"
                    ),
                    models.Index(
                        fields=["status"], name="services_se_status_9254ae_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.CharField(max_length=4, unique=True)),
                ("last_sequence", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Service Sequence",
                "verbose_name_plural": "Service Sequences",
                "indexes": [
                    models.Index(
                        fields=["year_month"], name="services_se_year_mo_ce4574_idx"
                    )
                ],
            },
        ),
    ]
