# Generated by Django 5.2.4 on 2026-07-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicerequest_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequest",
            name="user",
        ),
    ]
